# Day 31/84
# Machine Learning Workflow Basics

In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split


# --------------------------------------------------
# 1. Load Dataset
# --------------------------------------------------

iris = load_iris()

X = iris.data
y = iris.target

print("Dataset loaded successfully")

print("X shape:", X.shape)
print("y shape:", y.shape)


# --------------------------------------------------
# 2. Understand Features and Target
# --------------------------------------------------

print("\nFeature names:")
print(iris.feature_names)

print("\nTarget names:")
print(iris.target_names)


# --------------------------------------------------
# 3. Train-Test Split
# --------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


# --------------------------------------------------
# 4. Check Split
# --------------------------------------------------

print("\nTrain shape:")
print(X_train.shape, y_train.shape)

print("\nTest shape:")
print(X_test.shape, y_test.shape)


# --------------------------------------------------
# 5. Compare Target Distribution
# --------------------------------------------------

print("\nTraining target distribution:")

for class_id in sorted(set(y_train)):
    count = (y_train == class_id).sum()
    print(
        iris.target_names[class_id],
        ":", 
        count
    )


print("\nTesting target distribution:")

for class_id in sorted(set(y_test)):
    count = (y_test == class_id).sum()
    print(
        iris.target_names[class_id],
        ":",
        count
    )


# --------------------------------------------------
# 6. Basic ML Workflow
# --------------------------------------------------

print("\nML Workflow:")

workflow = [
    "1. Collect data",
    "2. Clean data",
    "3. Explore data",
    "4. Define X and y",
    "5. Split train/test data",
    "6. Train model",
    "7. Evaluate model",
    "8. Improve model"
]

for step in workflow:
    print(step)


print("\nDay 31 completed.")

Dataset loaded successfully
X shape: (150, 4)
y shape: (150,)

Feature names:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Target names:
['setosa' 'versicolor' 'virginica']

Train shape:
(120, 4) (120,)

Test shape:
(30, 4) (30,)

Training target distribution:
setosa : 40
versicolor : 40
virginica : 40

Testing target distribution:
setosa : 10
versicolor : 10
virginica : 10

ML Workflow:
1. Collect data
2. Clean data
3. Explore data
4. Define X and y
5. Split train/test data
6. Train model
7. Evaluate model
8. Improve model

Day 31 completed.


In [3]:
# Day 32/84
# First Machine Learning Model - Logistic Regression

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


# --------------------------------------------------
# 1. Load Dataset
# --------------------------------------------------

iris = load_iris()

X = iris.data
y = iris.target

print("=" * 50)
print("DAY 32 - LOGISTIC REGRESSION")
print("=" * 50)

print("\nDataset shape:")
print("X:", X.shape)
print("y:", y.shape)


# --------------------------------------------------
# 2. Train/Test Split
# --------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("\nTrain shape:", X_train.shape)
print("Test shape:", X_test.shape)


# --------------------------------------------------
# 3. Create Model
# --------------------------------------------------

model = LogisticRegression(
    max_iter=200
)


# --------------------------------------------------
# 4. Train Model
# --------------------------------------------------

model.fit(X_train, y_train)

print("\nModel trained successfully!")


# --------------------------------------------------
# 5. Make Predictions
# --------------------------------------------------

y_pred = model.predict(X_test)

print("\nPredictions:")
print(y_pred)

print("\nActual values:")
print(y_test)


# --------------------------------------------------
# 6. Compare Predictions
# --------------------------------------------------

print("\nPrediction comparison:")

for actual, predicted in zip(y_test, y_pred):

    actual_name = iris.target_names[actual]
    predicted_name = iris.target_names[predicted]

    print(
        f"Actual: {actual_name:<10} "
        f"Predicted: {predicted_name}"
    )


# --------------------------------------------------
# 7. Accuracy
# --------------------------------------------------

accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy:")
print(f"{accuracy:.2%}")


# --------------------------------------------------
# 8. Predict a New Flower
# --------------------------------------------------

new_flower = [[
    5.1,
    3.5,
    1.4,
    0.2
]]

prediction = model.predict(new_flower)

print("\nNew flower prediction:")
print(iris.target_names[prediction[0]])


print("\n" + "=" * 50)
print("DAY 32 COMPLETED")
print("=" * 50)

DAY 32 - LOGISTIC REGRESSION

Dataset shape:
X: (150, 4)
y: (150,)

Train shape: (120, 4)
Test shape: (30, 4)

Model trained successfully!

Predictions:
[0 2 1 1 0 1 0 0 2 1 2 2 2 1 0 0 0 1 1 2 0 2 1 2 2 2 1 0 2 0]

Actual values:
[0 2 1 1 0 1 0 0 2 1 2 2 2 1 0 0 0 1 1 2 0 2 1 2 2 1 1 0 2 0]

Prediction comparison:
Actual: setosa     Predicted: setosa
Actual: virginica  Predicted: virginica
Actual: versicolor Predicted: versicolor
Actual: versicolor Predicted: versicolor
Actual: setosa     Predicted: setosa
Actual: versicolor Predicted: versicolor
Actual: setosa     Predicted: setosa
Actual: setosa     Predicted: setosa
Actual: virginica  Predicted: virginica
Actual: versicolor Predicted: versicolor
Actual: virginica  Predicted: virginica
Actual: virginica  Predicted: virginica
Actual: virginica  Predicted: virginica
Actual: versicolor Predicted: versicolor
Actual: setosa     Predicted: setosa
Actual: setosa     Predicted: setosa
Actual: setosa     Predicted: setosa
Actual: versicolor 

In [5]:
# Day 33/84
# Model Evaluation - Confusion Matrix & Classification Metrics

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)


# --------------------------------------------------
# 1. Load Dataset
# --------------------------------------------------

iris = load_iris()

X = iris.data
y = iris.target

print("=" * 55)
print("DAY 33 - MODEL EVALUATION")
print("=" * 55)


# --------------------------------------------------
# 2. Train/Test Split
# --------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


# --------------------------------------------------
# 3. Create & Train Model
# --------------------------------------------------

model = LogisticRegression(
    max_iter=200
)

model.fit(X_train, y_train)

print("\nModel trained successfully!")


# --------------------------------------------------
# 4. Predictions
# --------------------------------------------------

y_pred = model.predict(X_test)


# --------------------------------------------------
# 5. Accuracy
# --------------------------------------------------

accuracy = accuracy_score(
    y_test,
    y_pred
)

print("\nAccuracy:")
print(f"{accuracy:.2%}")


# --------------------------------------------------
# 6. Confusion Matrix
# --------------------------------------------------

cm = confusion_matrix(
    y_test,
    y_pred
)

print("\nConfusion Matrix:")
print(cm)


# --------------------------------------------------
# 7. Explain Matrix
# --------------------------------------------------

print("\nClass order:")
print(iris.target_names)

print(
    "\nRows = Actual class"
    "\nColumns = Predicted class"
)


# --------------------------------------------------
# 8. Classification Report
# --------------------------------------------------

report = classification_report(
    y_test,
    y_pred,
    target_names=iris.target_names
)

print("\nClassification Report:")
print(report)


# --------------------------------------------------
# 9. Individual Metrics
# --------------------------------------------------

report_dict = classification_report(
    y_test,
    y_pred,
    target_names=iris.target_names,
    output_dict=True
)


print("\nIndividual Class Metrics:")

for class_name in iris.target_names:

    precision = report_dict[class_name]["precision"]
    recall = report_dict[class_name]["recall"]
    f1 = report_dict[class_name]["f1-score"]

    print(f"\n{class_name}")
    print(f"Precision: {precision:.2f}")
    print(f"Recall:    {recall:.2f}")
    print(f"F1-score:  {f1:.2f}")


# --------------------------------------------------
# 10. Prediction Summary
# --------------------------------------------------

correct = (y_test == y_pred).sum()
total = len(y_test)

print("\nPrediction Summary:")
print(f"Correct predictions: {correct}")
print(f"Total predictions:   {total}")
print(f"Wrong predictions:   {total - correct}")


print("\n" + "=" * 55)
print("DAY 33 COMPLETED")
print("=" * 55)

DAY 33 - MODEL EVALUATION

Model trained successfully!

Accuracy:
96.67%

Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]

Class order:
['setosa' 'versicolor' 'virginica']

Rows = Actual class
Columns = Predicted class

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      0.90      0.95        10
   virginica       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30


Individual Class Metrics:

setosa
Precision: 1.00
Recall:    1.00
F1-score:  1.00

versicolor
Precision: 1.00
Recall:    0.90
F1-score:  0.95

virginica
Precision: 0.91
Recall:    1.00
F1-score:  0.95

Prediction Summary:
Correct predictions: 29
Total predictions:   30
Wrong predictions:   1

DAY 33 COMPLETED


In [6]:
# ============================================================
# DAY 34/84 — FEATURE SCALING
# ============================================================

import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


print("=" * 60)
print("DAY 34 — FEATURE SCALING")
print("=" * 60)


# 1. Load dataset

iris = load_iris()

X = iris.data
y = iris.target


# 2. Train/Test Split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


# 3. See original data

print("\nOriginal data:")
print(np.round(X_train[:5], 2))


# 4. Create scaler

scaler = StandardScaler()


# 5. Fit ONLY on training data

X_train_scaled = scaler.fit_transform(X_train)


# 6. Transform test data

X_test_scaled = scaler.transform(X_test)


# 7. See scaled data

print("\nScaled data:")
print(np.round(X_train_scaled[:5], 2))


# 8. Check mean and standard deviation

print("\nScaled mean:")
print(np.round(X_train_scaled.mean(axis=0), 2))

print("\nScaled standard deviation:")
print(np.round(X_train_scaled.std(axis=0), 2))


# 9. Train model on scaled data

model = LogisticRegression(
    max_iter=200
)

model.fit(
    X_train_scaled,
    y_train
)


# 10. Predictions

y_pred = model.predict(X_test_scaled)


# 11. Accuracy

accuracy = accuracy_score(
    y_test,
    y_pred
)

print("\nAccuracy:")
print(f"{accuracy:.2%}")


print("\n" + "=" * 60)
print("DAY 34 COMPLETED")
print("=" * 60)

DAY 34 — FEATURE SCALING

Original data:
[[4.4 2.9 1.4 0.2]
 [4.9 2.5 4.5 1.7]
 [6.8 2.8 4.8 1.4]
 [4.9 3.1 1.5 0.1]
 [5.5 2.5 4.  1.3]]

Scaled data:
[[-1.72 -0.33 -1.35 -1.32]
 [-1.12 -1.23  0.41  0.65]
 [ 1.14 -0.56  0.58  0.26]
 [-1.12  0.12 -1.29 -1.45]
 [-0.41 -1.23  0.13  0.13]]

Scaled mean:
[-0. -0.  0.  0.]

Scaled standard deviation:
[1. 1. 1. 1.]

Accuracy:
93.33%

DAY 34 COMPLETED


In [2]:
# ============================================================
# DAY 35/84 — KNN + FEATURE SCALING
# ============================================================

import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score


print("=" * 60)
print("DAY 35 — KNN + FEATURE SCALING")
print("=" * 60)


# 1. Load dataset

iris = load_iris()

X = iris.data
y = iris.target


# 2. Split data

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


# ------------------------------------------------------------
# 3. KNN WITHOUT SCALING
# ------------------------------------------------------------

knn_raw = KNeighborsClassifier(
    n_neighbors=5
)

knn_raw.fit(
    X_train,
    y_train
)

pred_raw = knn_raw.predict(
    X_test
)

accuracy_raw = accuracy_score(
    y_test,
    pred_raw
)


print("\nKNN WITHOUT SCALING:")
print(f"Accuracy: {accuracy_raw:.2%}")


# ------------------------------------------------------------
# 4. Scale the data
# ------------------------------------------------------------

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(
    X_train
)

X_test_scaled = scaler.transform(
    X_test
)


# ------------------------------------------------------------
# 5. KNN WITH SCALING
# ------------------------------------------------------------

knn_scaled = KNeighborsClassifier(
    n_neighbors=5
)

knn_scaled.fit(
    X_train_scaled,
    y_train
)

pred_scaled = knn_scaled.predict(
    X_test_scaled
)

accuracy_scaled = accuracy_score(
    y_test,
    pred_scaled
)


print("\nKNN WITH SCALING:")
print(f"Accuracy: {accuracy_scaled:.2%}")


# ------------------------------------------------------------
# 6. Compare
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("COMPARISON")
print("=" * 60)

print(
    f"Without Scaling : {accuracy_raw:.2%}"
)

print(
    f"With Scaling    : {accuracy_scaled:.2%}"
)


# ------------------------------------------------------------
# 7. Test different K values
# ------------------------------------------------------------

print("\nK VALUE EXPERIMENT:")

for k in [1, 3, 5, 7, 9]:

    model = KNeighborsClassifier(
        n_neighbors=k
    )

    model.fit(
        X_train_scaled,
        y_train
    )

    predictions = model.predict(
        X_test_scaled
    )

    score = accuracy_score(
        y_test,
        predictions
    )

    print(
        f"k={k:<2} → {score:.2%}"
    )


print("\n" + "=" * 60)
print("DAY 35 COMPLETED")
print("=" * 60)

DAY 35 — KNN + FEATURE SCALING

KNN WITHOUT SCALING:
Accuracy: 100.00%

KNN WITH SCALING:
Accuracy: 93.33%

COMPARISON
Without Scaling : 100.00%
With Scaling    : 93.33%

K VALUE EXPERIMENT:
k=1  → 96.67%
k=3  → 93.33%
k=5  → 93.33%
k=7  → 96.67%
k=9  → 96.67%

DAY 35 COMPLETED


In [4]:
# ============================================================
# DAY 36/84 — HYPERPARAMETER TUNING
# ============================================================

from sklearn.datasets import load_iris
from sklearn.model_selection import (
    train_test_split,
    GridSearchCV
)

from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score


print("=" * 60)
print("DAY 36 — HYPERPARAMETER TUNING")
print("=" * 60)


# ------------------------------------------------------------
# 1. Load dataset
# ------------------------------------------------------------

iris = load_iris()

X = iris.data
y = iris.target


# ------------------------------------------------------------
# 2. Train/Test Split
# ------------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


# ------------------------------------------------------------
# 3. Create Pipeline
# ------------------------------------------------------------

pipeline = Pipeline([
    (
        "scaler",
        StandardScaler()
    ),

    (
        "knn",
        KNeighborsClassifier()
    )
])


# ------------------------------------------------------------
# 4. Define Hyperparameters
# ------------------------------------------------------------

param_grid = {

    "knn__n_neighbors": [
        1,
        3,
        5,
        7,
        9,
        11
    ],

    "knn__weights": [
        "uniform",
        "distance"
    ],

    "knn__metric": [
        "euclidean",
        "manhattan"
    ]
}


# ------------------------------------------------------------
# 5. GridSearchCV
# ------------------------------------------------------------

grid_search = GridSearchCV(
    pipeline,
    param_grid,
    cv=5,
    scoring="accuracy"
)


# ------------------------------------------------------------
# 6. Train Search
# ------------------------------------------------------------

grid_search.fit(
    X_train,
    y_train
)


# ------------------------------------------------------------
# 7. Best Parameters
# ------------------------------------------------------------

print("\nBest parameters:")

print(
    grid_search.best_params_
)


# ------------------------------------------------------------
# 8. Best Cross Validation Score
# ------------------------------------------------------------

print("\nBest CV accuracy:")

print(
    f"{grid_search.best_score_:.2%}"
)


# ------------------------------------------------------------
# 9. Test Best Model
# ------------------------------------------------------------

best_model = grid_search.best_estimator_

y_pred = best_model.predict(
    X_test
)


# ------------------------------------------------------------
# 10. Test Accuracy
# ------------------------------------------------------------

test_accuracy = accuracy_score(
    y_test,
    y_pred
)

print("\nTest accuracy:")

print(
    f"{test_accuracy:.2%}"
)


# ------------------------------------------------------------
# 11. Show Top Results
# ------------------------------------------------------------

results = grid_search.cv_results_

scores = results["mean_test_score"]
params = results["params"]

top_indices = scores.argsort()[-5:][::-1]

print("\nTop 5 configurations:")

for index in top_indices:

    print(
        f"{scores[index]:.2%} → "
        f"{params[index]}"
    )


print("\n" + "=" * 60)
print("DAY 36 COMPLETED")
print("=" * 60)

DAY 36 — HYPERPARAMETER TUNING

Best parameters:
{'knn__metric': 'euclidean', 'knn__n_neighbors': 5, 'knn__weights': 'uniform'}

Best CV accuracy:
96.67%

Test accuracy:
93.33%

Top 5 configurations:
96.67% → {'knn__metric': 'euclidean', 'knn__n_neighbors': 5, 'knn__weights': 'uniform'}
96.67% → {'knn__metric': 'euclidean', 'knn__n_neighbors': 5, 'knn__weights': 'distance'}
96.67% → {'knn__metric': 'euclidean', 'knn__n_neighbors': 11, 'knn__weights': 'distance'}
96.67% → {'knn__metric': 'euclidean', 'knn__n_neighbors': 9, 'knn__weights': 'distance'}
95.83% → {'knn__metric': 'manhattan', 'knn__n_neighbors': 11, 'knn__weights': 'distance'}

DAY 36 COMPLETED
