In [ ]:
import numpy as np
import matplotlib.pyplot as plt

print(np.__version__)


In [ ]:
print("NumPy Version:", np.__version__)


In [ ]:
import numpy as np

print(np.__version__)


In [ ]:
arr = np.arange(1,13)

print(arr)

In [ ]:
arr = arr.reshape(3,4)

arr

In [ ]:
print("Shape :", arr.shape)
print("Size :", arr.size)
print("Datatype :", arr.dtype)
print("Dimension :", arr.ndim)
print("Item Size :", arr.itemsize)

In [ ]:
print(np.ones((3,3)))

print(np.zeros((2,4)))

print(np.identity(4))

print(np.ones((3,3)))

print(np.zeros((2,4)))

print(np.identity(4))

In [ ]:
print(np.ones((3,3)))

print(np.zeros((2,4)))

print(np.identity(4))

In [ ]:
random_array = np.random.randint(1,100,(4,4))

random_array

In [ ]:
a = np.arange(12).reshape(2,6)

b = np.arange(12,24).reshape(6,2)

np.dot(a,b)

In [ ]:
import matplotlib.pyplot as plt

x = np.linspace(-10,10,100)

y = np.sin(x)

plt.plot(x,y)

plt.title("Sine Wave")

plt.xlabel("X")

plt.ylabel("sin(x)")

plt.grid(True)

plt.show()

In [ ]:
# ==============================
# Day 3 - NumPy Indexing & Slicing
# ==============================

import numpy as np

# Create a 3x4 array
arr = np.arange(1,13).reshape(3,4)

print("Original Array:")
print(arr)

# ------------------------------
# Indexing
# ------------------------------

print("\nFirst Row:")
print(arr[0])

print("\nSecond Row:")
print(arr[1])

print("\nFirst Element:")
print(arr[0,0])

print("\nLast Element:")
print(arr[-1,-1])

# ------------------------------
# Slicing
# ------------------------------

print("\nFirst Two Columns:")
print(arr[:,0:2])

print("\nLast Two Rows:")
print(arr[1:,:])

print("\nMiddle Elements:")
print(arr[:,1:3])

# ------------------------------
# Boolean Masking
# ------------------------------

print("\nElements Greater Than 6:")
print(arr[arr > 6])

print("\nEven Numbers:")
print(arr[arr % 2 == 0])

# ------------------------------
# Fancy Indexing
# ------------------------------

print("\nFirst and Third Row:")
print(arr[[0,2]])

print("\nColumns 1 and 3:")
print(arr[:,[0,2]])

# ------------------------------
# Iteration
# ------------------------------

print("\nIterating through Array:")

for row in arr:
    print(row)

# ------------------------------
# Mini Challenge
# ------------------------------

marks = np.array([35,78,91,44,67,82,29,99,56,73])

print("\nStudent Marks:")
print(marks)

print("Highest Marks:", np.max(marks))
print("Lowest Marks:", np.min(marks))
print("Average Marks:", np.mean(marks))

print("Marks Above 75:")
print(marks[marks > 75])

print("Marks Below 40:")
print(marks[marks < 40])

print("Sorted Marks:")
print(np.sort(marks))

In [ ]:
# -----------------------------
# Broadcasting with Arrays
# -----------------------------

a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])

print("\nBroadcasting Result:")
print(a + b)


In [ ]:
# -----------------------------
# Vectorized Operations
# -----------------------------

numbers = np.arange(1, 11)

print("\nNumbers:")
print(numbers)

print("\nSquare:")
print(numbers ** 2)

print("\nCube:")
print(numbers ** 3)

print("\nSquare Root:")
print(np.sqrt(numbers))

In [ ]:
# -----------------------------
# Conditional Operations
# -----------------------------

print("\nNumbers Greater Than 5:")
print(numbers[numbers > 5])

print("\nEven Numbers:")
print(numbers[numbers % 2 == 0])

# -----------------------------
# Universal Functions (ufuncs)
# -----------------------------

angles = np.array([0, np.pi/2, np.pi])

print("\nSin:")
print(np.sin(angles))

print("\nCos:")
print(np.cos(angles))

print("\nLog:")
print(np.log(np.array([1, 10, 100])))

print("\nExponential:")
print(np.exp(np.array([1, 2, 3])))

In [ ]:
# -----------------------------
# Practice Challenge
# -----------------------------

marks = np.array([45, 67, 89, 91, 34, 76, 55, 99])

print("\nOriginal Marks:")
print(marks)

print("\nBonus +5:")
print(marks + 5)

print("\nStudents Above 75:")
print(marks[marks > 75])

print("\nAverage:")
print(np.mean(marks))

print("\nMaximum:")
print(np.max(marks))

print("\nSorted:")
print(np.sort(marks))

In [ ]:
# ==========================================
# Day 5 - Stacking, Splitting, Sorting & Searching
# ==========================================

import numpy as np

# ---------------------------------
# Vertical Stack
# ---------------------------------

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

print("Vertical Stack")
print(np.vstack((a, b)))

# ---------------------------------


In [ ]:
# ---------------------------------
# Horizontal Stack
# ---------------------------------

print("\nHorizontal Stack")
print(np.hstack((a, b)))

In [ ]:
# ---------------------------------
# Splitting Arrays
# ---------------------------------

arr = np.arange(1, 13)

print("\nSplit into 3 parts")
print(np.split(arr, 3))


In [ ]:
# ---------------------------------
# Sorting
# ---------------------------------

marks = np.array([78, 45, 99, 32, 67, 81])

print("\nOriginal")
print(marks)

print("\nSorted")
print(np.sort(marks))


In [ ]:
# ---------------------------------
# Unique Values
# ---------------------------------

arr2 = np.array([1,2,2,3,4,4,5,6,6])

print("\nUnique Values")
print(np.unique(arr2))

In [ ]:
# ---------------------------------
# Count Non-Zero
# ---------------------------------

arr3 = np.array([0,1,2,0,3,0,4])

print("\nNon Zero Count")
print(np.count_nonzero(arr3))


In [ ]:
# ---------------------------------
# Practice Challenge
# ---------------------------------

sales = np.array([230,150,420,300,520,180])

print("\nHighest Sale:", np.max(sales))
print("Lowest Sale:", np.min(sales))
print("Average Sale:", np.mean(sales))
print("Sorted Sales:", np.sort(sales))

In [ ]:
# -----------------------------
# Matrix Addition
# -----------------------------

print("\nMatrix Addition:")
print(A + B)

# -----------------------------
# Matrix Subtraction
# -----------------------------

print("\nMatrix Subtraction:")
print(A - B)

# -----------------------------
# Matrix Multiplication
# -----------------------------

print("\nMatrix Multiplication:")
print(np.dot(A, B))


In [ ]:

# -----------------------------
# Transpose
# -----------------------------

print("\nTranspose of A:")
print(A.T)

# -----------------------------
# Determinant
# -----------------------------

print("\nDeterminant of A:")
print(np.linalg.det(A))

# -----------------------------
# Inverse
# -----------------------------

C = np.array([[4, 7],
              [2, 6]])

print("\nMatrix C:")
print(C)

print("\nInverse of C:")
print(np.linalg.inv(C))


In [ ]:
# -----------------------------
# Rank
# -----------------------------

print("\nRank of C:")
print(np.linalg.matrix_rank(C))

# -----------------------------
# Trace
# -----------------------------

print("\nTrace of C:")
print(np.trace(C))

# -----------------------------
# Eigenvalues & Eigenvectors
# -----------------------------

values, vectors = np.linalg.eig(C)

print("\nEigenvalues:")
print(values)

print("\nEigenvectors:")
print(vectors)

In [ ]:
import numpy as np

# -----------------------------
# Practice Challenge
# -----------------------------

# -----------------------------
# Practice Challenge
# -----------------------------

marks = np.array([[80, 90],
                  [70, 85]])

bonus = np.array([[5, 5],
                  [5, 5]])

print("\nMarks After Bonus:")
print(marks + bonus)

bonus = np.array([[5, 5],
                  [5, 5]])

print("\nMarks After Bonus:")
print(marks + bonus)

In [ ]:
import numpy as np
a=np.arange(1,19).reshape(2,9)
a.size
a.ndim
a.astype(np.int32)
a.dtype
a*2
a>10

In [ ]:
import numpy as np
a=np.arange(10000000)
a


In [ ]:
import numpy as np  
import sys
a=np.arange(10000000,dtype=np.int8)
sys.getsizeof(a)

In [ ]:
a[[0,2,5]]
a

In [ ]:
a=np.random.randint(1,100,24).reshape(6,4)
a

In [ ]:
arr = np.arange(0,20,2)
arr%2==0

In [15]:
import numpy as np
a=np.arange(20).reshape(4,5)


In [49]:
a1=np.arange(10,30).reshape(4,5)
a+a1
a2 = np.random.random((3,3))
a2 = np.round(a2*100)
a2=np.arange(30,50).reshape(5,4)
np.max(a2,axis = 0)
np.sum(a2,axis=0)
np.mean(a2,axis = 1)
np.std(a2,axis=0)
np.var(a2,axis=0)
np.max(a2)
np.min(a2)
np.dot(a1,a2)

array([[2320, 2380, 2440, 2500],
       [3270, 3355, 3440, 3525],
       [4220, 4330, 4440, 4550],
       [5170, 5305, 5440, 5575]])

Create a NumPy array containing numbers from 1 to 20.


In [53]:
arr = np.arange(1,21)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Create a 5 × 5 matrix filled with ones.

In [55]:
import numpy as np

arr = np.zeros((5,5))
arr

Create a 4 × 4 matrix filled with ones.

In [59]:
arr = np.ones((4,4), dtype = np.int32)
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

Q4 Create a 6 × 6 Identity Matrix.

In [62]:
arr = np.identity(6)
arr

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

Without manually typing the numbers, create this array:

[2 4 6 8 10 12 14 16 18 20]

In [74]:
arr = np.arange(1,21)
arr = arr[arr % 2 == 0]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

🚀 Section B – Array Attributes

Create this array first:

arr = np.arange(1, 26).reshape(5,5)

Q6 Print only the shape of the array.

In [76]:
arr = np.arange(1, 26).reshape(5,5)
np.shape(arr)

(5, 5)

🎯 Q7 Using the same array:

arr = np.arange(1,26).reshape(5,5)

Print the number of dimensions of the array.

In [77]:
arr = np.arange(1,26).reshape(5,5)
arr.ndim

2

🚀 Q8 Using the same array:

arr = np.arange(1,26).reshape(5,5)

Print the total number of elements in the array.

In [86]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

🚀Q9

arr = np.arange(1,26).reshape(5,5)

Print the datatype of the array.

In [87]:
arr = np.arange(1,26).reshape(5,5)
arr.dtype

dtype('int64')

🚀 Q10 (Last Question of Attributes)

Using the same array:

arr = np.arange(1,26).reshape(5,5)

Print the memory occupied by one element.

In [ ]:
arr = np.arange(1,26).reshape(5,5)
arr.itemsize

8

In [100]:
arr = np.arange(1,26).reshape(5,5)
arr[0]

array([1, 2, 3, 4, 5])

In [101]:
arr[:,0]


array([ 1,  6, 11, 16, 21])